name: quality-guardian
services:
  backend:
    container_name: qms-backend
    deploy:
      resources:
        limits:
          cpus: 1
          memory: '1073741824'
        reservations:
          memory: '536870912'
    environment:
      DATABASE_URL: mysql://quality_guard:178025249aA..@113.31.111.152:3306/quality_guard?connection_limit=10&pool_timeout=60
      JWT_ACCESS_SECRET: 0c696a863a71f071114812430a05727e4fe2ed40f4667a2042c6256db3ee579a
      JWT_REFRESH_SECRET: 4f19cc4d22c74d4470ae10ca984ff79d526e60b2b3e12b966d1876c160533e9b94d0aee58c6f167375b2274acc33bf68af547111019278afda379fa98bae866f
      NODE_ENV: production
      PORT: '3000'
      PRODUCTION_URL: http://localhost:3000
      REDIS_URL: redis://redis:6379
    image: crpi-jy3d0qwkxxv0twpn.cn-beijing.personal.cr.aliyuncs.com/ajie5419/qms:backend-latest
    logging:
      driver: json-file
      options:
        max-file: '3'
        max-size: 100m
    networks:
      qms-network: null
    ports:
      - mode: ingress
        host_ip: 127.0.0.1
        target: 3000
        published: '3000'
        protocol: tcp
    restart: always
    volumes:
      - type: volume
        source: qms-uploads
        target: /app/uploads
        volume: {}
  frontend:
    container_name: qms-frontend
    depends_on:
      backend:
        condition: service_started
        required: true
    image: crpi-jy3d0qwkxxv0twpn.cn-beijing.personal.cr.aliyuncs.com/ajie5419/qms:frontend-latest
    logging:
      driver: json-file
      options:
        max-file: '3'
        max-size: 50m
    networks:
      qms-network: null
    ports:
      - mode: ingress
        target: 80
        published: '80'
        protocol: tcp
    restart: always
    volumes:
      - type: volume
        source: qms-uploads
        target: /usr/share/nginx/html/uploads
        volume: {}
  redis:
    command:
      - redis-server
      - --appendonly
      - 'yes'
    container_name: qms-redis
    image: redis:alpine
    networks:
      qms-network: null
    restart: always
    volumes:
      - type: volume
        source: qms-redis-data
        target: /data
        volume: {}
networks:
  qms-network:
    name: qms-network
    driver: bridge
volumes:
  qms-redis-data:
    name: quality-guardian_qms-redis-data
    driver: local
  qms-uploads:
    name: quality-guardian_qms-uploads
    driver: local
