name: quality-guardian
services:
  backend:
    build:
      context: 
      dockerfile: Dockerfile.backend
    container_name: qms-backend
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 
        reservations:
          memory: 
    environment:
      DATABASE_URL: 
      JWT_ACCESS_SECRET: 
      JWT_REFRESH_SECRET: 
      NODE_ENV: production
      PORT: '3000'
      PRODUCTION_URL: http://localhost:3000
      REDIS_URL: redis://redis:6379
    image: 
    logging:
      driver: json-file
      options:
        max-file: '3'
        max-size: 100m
    networks:
      qms-network: null
    ports:
      - mode: ingress
        host_ip: 127.0.0.1
        target: 3000
        published: '3000'
        protocol: tcp
    restart: always
    volumes:
      - type: volume
        source: qms-uploads
        target: /app/uploads
        volume: {}
  frontend:
    build:
      context: 
      dockerfile: Dockerfile.frontend
    container_name: qms-frontend
    depends_on:
      backend:
        condition: service_started
        required: true
    environment:
      DATABASE_URL: 
      JWT_ACCESS_SECRET:
      JWT_REFRESH_SECRET: 
      NODE_ENV: production
      PRODUCTION_URL: http://localhost:3000
      REDIS_URL: redis://redis:6379
    image: 
    logging:
      driver: json-file
      options:
        max-file: '3'
        max-size: 50m
    networks:
      qms-network: null
    ports:
      - mode: ingress
        target: 80
        published: '80'
        protocol: tcp
    restart: always
    volumes:
      - type: volume
        source: qms-uploads
        target: /usr/share/nginx/html/uploads
        volume: {}
  redis:
    command:
      - redis-server
      - --appendonly
      - 'yes'
    container_name: qms-redis
    image: redis:alpine
    networks:
      qms-network: null
    restart: always
    volumes:
      - type: volume
        source: qms-redis-data
        target: /data
        volume: {}
networks:
  qms-network:
    name: qms-network
    driver: bridge
volumes:
  qms-redis-data:
    name: quality-guardian_qms-redis-data
    driver: local
  qms-uploads:
    name: quality-guardian_qms-uploads
    driver: local
