export const QUALITY_LOSS_LIST = [
  {
    id: 'QL-2024001',
    date: '2024-05-10',
    type: 'Scrap',
    amount: 5000,
    description: 'Component A defect scraping',
    responsibleDepartment: 'Production',
    status: 'Confirmed',
  },
  {
    id: 'QL-2024002',
    date: '2024-05-12',
    type: 'Rework',
    amount: 1200,
    description: 'Assembly line rework due to sensor issue',
    responsibleDepartment: 'Quality',
    status: 'Pending',
  },
  {
    id: 'QL-2024003',
    date: '2024-05-15',
    type: 'Return',
    amount: 8500,
    description: 'Customer return batch #9982',
    responsibleDepartment: 'Sales',
    status: 'Processing',
  },
];

export const WORK_ORDER_LIST = [
  {
    id: 'WO-2024001',
    workOrderNumber: 'WO-2024001',
    customerName: 'Acme Corp',
    quantity: 50,
    deliveryDate: '2024-05-20',
    status: '进行中',
    createTime: '2024-05-10 09:30:00',
    division: '桥梁 SOBU',
  },
  {
    id: 'WO-2024002',
    workOrderNumber: 'WO-2024002',
    customerName: 'Beta Inc',
    quantity: 120,
    deliveryDate: '2024-05-22',
    status: '未开始',
    createTime: '2024-05-12 14:15:00',
    division: '车辆 SOBU',
  },
  {
    id: 'WO-2024003',
    workOrderNumber: 'WO-2024003',
    customerName: 'Gamma Ltd',
    quantity: 200,
    deliveryDate: '2024-05-18',
    status: '已完成',
    createTime: '2024-05-08 11:00:00',
    division: '海外 SOBU',
  },
];

export const INSPECTION_ISSUES_LIST = [
  {
    id: 'ISS-2024-001',
    workOrderNumber: 'WO-2024001',
    projectName: 'Excavator Model K10',
    partName: 'Main Chassis Frame',
    ncNumber: 'NC-2024-055',
    title: 'Mismatch in dimension tolerance',
    severity: 'Critical',
    status: 'Open',
    quantity: 5,
    reportedBy: 'Inspector A',
    responsibleDepartment: 'Welding',
    reportDate: '2024-05-25',
    updatedAt: '2024-05-25 10:00:00',
    description: 'Dimension X is out of expected range (5mm vs 4.5mm).',
    rootCause: 'Machine calibration error',
    solution: 'Recalibrate machine and rework parts',
    lossAmount: 2000,
    claim: 'No',
    photos: [],
    division: '桥梁 SOBU',
    defectType: '制造缺陷',
    defectSubtype: '加工精度缺陷',
  },
  {
    id: 'ISS-2024-002',
    workOrderNumber: 'WO-2024005',
    projectName: 'Loader Type L5',
    partName: 'Side Panel',
    ncNumber: 'NC-2024-058',
    title: 'Surface scratch on chassis',
    severity: 'Minor',
    status: 'Closed',
    quantity: 12,
    reportedBy: 'Inspector B',
    responsibleDepartment: 'Painting',
    reportDate: '2024-05-26',
    updatedAt: '2024-05-27 14:30:00',
    description: 'Small scratch detected on the rear panel.',
    rootCause: 'Handling damage during transport',
    solution: 'Touch up painting',
    lossAmount: 150,
    claim: 'Yes',
    photos: [],
    division: '车辆 SOBU',
    defectType: '零部件缺陷',
    defectSubtype: '外观问题',
  },
];

export const INCOMING_INSPECTION_LIST = [
  {
    id: '1',
    supplierName: 'Steel Works Ltd',
    materialName: 'Steel Sheet 5mm',
    quantity: 100,
    inspector: 'John Doe',
    reporter: 'Alice',
    reportDate: '2024-06-01',
    hasDocuments: '有',
  },
  {
    id: '2',
    supplierName: 'ElectroComponents Inc',
    materialName: 'Sensor Module',
    quantity: 50,
    inspector: 'Jane Smith',
    reporter: 'Bob',
    reportDate: '2024-06-02',
    hasDocuments: '无',
  },
];

export const PROCESS_INSPECTION_LIST = [
  {
    id: '1',
    workOrderNumber: 'WO-2024001',
    process: '焊接',
    level1Component: 'Main Frame',
    componentName: 'Chassis',
    quantity: 5,
    inspector: 'Mike Brown',
    reporter: 'Charlie',
    team: 'Team A',
    archived: '是',
  },
  {
    id: '2',
    workOrderNumber: 'WO-2024002',
    process: '装配',
    level1Component: 'Hydraulic System',
    componentName: 'Pump Assembly',
    quantity: 10,
    inspector: 'Sarah',
    reporter: 'David',
    team: 'Team B',
    archived: '否',
  },
];

export const SHIPMENT_INSPECTION_LIST = [
  {
    id: '1',
    workOrderNumber: 'WO-2024001',
    projectName: 'Excavator Model K10',
    quantity: 5,
    reporter: 'Eve',
    inspector: 'Frank',
    reportDate: '2024-06-10',
    documents: 'Full Set',
    packingListArchived: '是',
  },
  {
    id: '2',
    workOrderNumber: 'WO-2024003',
    projectName: 'Loader Type L5',
    quantity: 2,
    reporter: 'Grace',
    inspector: 'Heidi',
    reportDate: '2024-06-12',
    documents: 'Partial',
    packingListArchived: '是',
  },
];

export const DFMEA_PROJECTS_LIST = [
  {
    id: 'PROJ-001',
    projectName: '液压泵 X1 项目',
    workOrderId: 'WO-2024001',
    version: 'V1.0',
    status: 'active',
    description: '液压泵核心组件的 DFMEA 分析',
    createdAt: '2024-05-01T00:00:00.000Z',
    updatedAt: '2024-05-15T00:00:00.000Z',
    createdBy: 'admin',
  },
  {
    id: 'PROJ-002',
    projectName: '控制阀 V2 项目',
    workOrderId: 'WO-2024002',
    version: 'V1.2',
    status: 'active',
    description: '智能控制系统的 DFMEA 分析',
    createdAt: '2024-05-05T00:00:00.000Z',
    updatedAt: '2024-05-20T00:00:00.000Z',
    createdBy: 'admin',
  },
  {
    id: 'PROJ-003',
    projectName: '传感器模块 S5 项目',
    workOrderId: 'WO-2024003',
    version: 'V2.0',
    status: 'draft',
    description: '新型传感器模块的 DFMEA 分析',
    createdAt: '2024-05-10T00:00:00.000Z',
    updatedAt: '2024-05-25T00:00:00.000Z',
    createdBy: 'admin',
  },
];

export const DFMEA_LIST = [
  {
    id: 'DFMEA-001',
    projectId: 'PROJ-001',
    item: 'Hydraulic Seal',
    function: 'Prevent leak',
    failureMode: 'Seal rupture',
    effects: 'Loss of pressure',
    severity: 8,
    occurrence: 3,
    detection: 4,
    rpn: 96,
    order: 1,
  },
  {
    id: 'DFMEA-002',
    projectId: 'PROJ-001',
    item: 'Pump Housing',
    function: 'Contain fluid',
    failureMode: 'Crack formation',
    effects: 'Fluid leakage',
    severity: 7,
    occurrence: 2,
    detection: 3,
    rpn: 42,
    order: 2,
  },
  {
    id: 'DFMEA-003',
    projectId: 'PROJ-001',
    item: 'Pressure Relief Valve',
    function: 'Prevent overpressure',
    failureMode: 'Valve stuck',
    effects: 'System damage',
    severity: 9,
    occurrence: 3,
    detection: 5,
    rpn: 135,
    order: 3,
  },
  {
    id: 'DFMEA-004',
    projectId: 'PROJ-002',
    item: 'Circuit Board',
    function: 'Signal processing',
    failureMode: 'Short circuit',
    effects: 'System failure',
    severity: 9,
    occurrence: 2,
    detection: 3,
    rpn: 54,
    order: 1,
  },
  {
    id: 'DFMEA-005',
    projectId: 'PROJ-002',
    item: 'Control Chip',
    function: 'Process control',
    failureMode: 'Overheating',
    effects: 'Performance degradation',
    severity: 6,
    occurrence: 4,
    detection: 4,
    rpn: 96,
    order: 2,
  },
];

export const BOM_PROJECTS_LIST = [
  {
    id: 'BOM-PROJ-001',
    projectName: '液压泵 X1 核心模组',
    workOrderNumber: 'WO-2024001',
    version: 'V1.0',
    status: 'active',
    description: '液压泵主控单元及密封组件',
    createdAt: '2024-05-01 09:00:00',
    updatedAt: '2024-05-15 14:30:00',
    createdBy: 'admin',
  },
  {
    id: 'BOM-PROJ-002',
    projectName: '控制阀 V2 动力总成',
    workOrderNumber: 'WO-2024002',
    version: 'V1.1',
    status: 'draft',
    description: '高压控制阀组及传动机构',
    createdAt: '2024-05-10 10:00:00',
    updatedAt: '2024-05-20 11:00:00',
    createdBy: 'admin',
  },
];

export const BOM_LIST = [
  {
    id: 'BOM-1001',
    projectId: 'BOM-PROJ-001',
    partNumber: 'PN-12345',
    partName: 'Main Chassis',
    version: 'V1.0',
    quantity: 1,
    unit: 'PCS',
    material: 'Steel',
    remarks: '主架构部件',
  },
  {
    id: 'BOM-1002',
    projectId: 'BOM-PROJ-001',
    partNumber: 'PN-67890',
    partName: 'Fixing Screw',
    version: 'V2.1',
    quantity: 12,
    unit: 'PCS',
    material: 'SS304',
    remarks: '不锈钢紧固螺钉',
  },
  {
    id: 'BOM-1003',
    projectId: 'BOM-PROJ-002',
    partNumber: 'PN-88888',
    partName: 'Valve Body',
    version: 'V1.0',
    quantity: 1,
    unit: 'PCS',
    material: 'Aluminum',
    remarks: '阀体铸件',
  },
];

export const ITP_PROJECTS_LIST = [
  {
    id: 'ITP-PROJ-001',
    projectName: '液压泵 X1 检验计划',
    workOrderId: 'WO-2024001',
    version: 'V1.0',
    status: 'active',
    description: '液压泵生产全过程检验计划',
    createdAt: '2024-05-01 09:00:00',
    updatedAt: '2024-05-15 14:30:00',
    createdBy: 'admin',
  },
  {
    id: 'ITP-PROJ-002',
    projectName: '控制阀 V2 检验计划',
    workOrderId: 'WO-2024002',
    version: 'V1.1',
    status: 'draft',
    description: '关键控制阀件的专项检验',
    createdAt: '2024-05-10 10:00:00',
    updatedAt: '2024-05-20 11:00:00',
    createdBy: 'admin',
  },
];

export const ITP_LIST = [
  {
    id: 'ITP-ITEM-001',
    projectId: 'ITP-PROJ-001',
    processStep: '下料',
    activity: '钢板材质检查',
    referenceDoc: 'GB/T 700-2006',
    acceptanceCriteria: '材质证书齐全，厚度公差在±0.5mm内',
    controlPoint: 'R',
    frequency: '100%',
    verifyingDocument: '材质检验报告',
    isQuantitative: true,
    standardValue: 20,
    upperTolerance: 0.5,
    lowerTolerance: 0.5,
    unit: 'mm',
    order: 1,
  },
  {
    id: 'ITP-ITEM-002',
    projectId: 'ITP-PROJ-001',
    processStep: '焊接',
    activity: '焊缝尺寸检查',
    referenceDoc: 'AWS D1.1',
    acceptanceCriteria: '焊缝高度 8±1mm',
    controlPoint: 'W',
    frequency: '20%',
    verifyingDocument: '焊接检验记录',
    isQuantitative: true,
    standardValue: 8,
    upperTolerance: 1,
    lowerTolerance: 1,
    unit: 'mm',
    order: 2,
  },
  {
    id: 'ITP-ITEM-003',
    projectId: 'ITP-PROJ-001',
    processStep: '焊接',
    activity: '无损探伤 (UT)',
    referenceDoc: 'SOP-UT-001',
    acceptanceCriteria: '符合 I 级焊缝要求',
    controlPoint: 'H',
    frequency: '100%',
    verifyingDocument: 'UT 探伤报告',
    isQuantitative: false,
    order: 3,
  },
];

export const AFTER_SALES_LIST = [
  {
    id: '1',
    workOrderNumber: 'WO-2024001',
    projectName: 'Excavator K10 Project',
    customerName: 'Acme Corp',
    location: 'Shanghai Site A',
    factoryDate: '2023-01-15',
    warrantyStatus: '在保',
    issueDescription: 'Hydraulic pump leak',
    quantity: 1,
    issueDate: '2024-06-01',
    handler: 'John Doe',
    resolutionPlan: 'Replace seal',
    responsibleDept: 'Assembly',
    materialCost: 200,
    laborTravelCost: 500,
    closeDate: '2024-06-05',
    status: '已结束',
    defectType: '制造装配缺陷',
    severity: 'P1 级',
    defectSubtype: '焊接缺陷',
    productType: '车辆产品',
    productSubtype: '平板车',
    runningHours: 1200,
    division: '桥梁 SOBU',
  },
  {
    id: '2',
    workOrderNumber: 'WO-2024002',
    projectName: 'Loader L5 Project',
    customerName: 'Beta Inc',
    location: 'Beijing Site B',
    factoryDate: '2022-11-20',
    warrantyStatus: '过保',
    issueDescription: 'Engine overheating',
    quantity: 2,
    issueDate: '2024-06-10',
    handler: 'Jane Smith',
    resolutionPlan: 'Clean radiator',
    responsibleDept: 'After-sales',
    materialCost: 0,
    laborTravelCost: 800,
    closeDate: '',
    status: '处理中',
    defectType: '维护保养不当',
    severity: 'P2 级',
    defectSubtype: '润滑不及时',
    productType: '路桥产品',
    productSubtype: '其他',
    runningHours: 3500,
    division: '车辆 SOBU',
  },
];

export const SUPPLIER_LIST = [
  {
    id: 'SUP-001',
    category: '原材料',
    name: '武汉钢铁有限公司',
    productName: 'Q345B钢板',
    brand: '武钢',
    origin: '中国湖北',
    project: '桥梁项目A',
    buyer: '张三',
    score2025: 92,
  },
  {
    id: 'SUP-002',
    category: '零部件',
    name: '西门子电气有限公司',
    productName: 'PLC控制器',
    brand: 'SIEMENS',
    origin: '德国',
    project: '车辆项目B',
    buyer: '李四',
    score2025: 88,
  },
  {
    id: 'SUP-003',
    category: '配件',
    name: '浙江橡胶制品厂',
    productName: '密封圈',
    brand: '浙橡',
    origin: '中国浙江',
    project: '海外项目C',
    buyer: '王五',
    score2025: 75,
  },
];

export const KNOWLEDGE_CATEGORIES = [
  {
    id: 'CAT-001',
    name: '标准法规',
    description: 'ISO标准、国家标准及行业规范',
    children: [
      { id: 'CAT-001-001', name: 'ISO 9001', parentId: 'CAT-001' },
      { id: 'CAT-001-002', name: '行业标准', parentId: 'CAT-001' },
    ],
  },
  {
    id: 'CAT-002',
    name: '体系文件',
    description: '质量手册、程序文件及作业指导书',
    children: [
      { id: 'CAT-002-001', name: '质量手册', parentId: 'CAT-002' },
      { id: 'CAT-002-002', name: 'SOP 程序文件', parentId: 'CAT-002' },
      { id: 'CAT-002-003', name: 'WI 作业指导书', parentId: 'CAT-002' },
    ],
  },
  {
    id: 'CAT-003',
    name: '经验教训 (LL)',
    description: '典型案例、故障分析及改进记录',
    children: [
      { id: 'CAT-003-001', name: 'NCR 案例', parentId: 'CAT-003' },
      { id: 'CAT-003-002', name: '8D 报告', parentId: 'CAT-003' },
    ],
  },
];

export const KNOWLEDGE_LIST = [
  {
    id: 'KB-1001',
    title: 'ISO 9001:2015 质量管理体系要求',
    categoryId: 'CAT-001-001',
    categoryName: 'ISO 9001',
    tags: ['ISO', '管理体系'],
    author: '质量管理部',
    publishDate: '2024-01-15',
    summary: '本标准为有下列需求的组织规定了质量管理体系要求。',
    content:
      '<h1>ISO 9001:2015 核心内容</h1><p>组织应确定与其宗旨和战略方向相关...</p>',
    status: 'published',
    version: 'V1.0',
    updatedAt: '2024-01-15 10:00:00',
    attachments: [
      { name: 'ISO9001-2015.pdf', url: '#', size: 102_400, type: 'pdf' },
    ],
  },
  {
    id: 'KB-1002',
    title: '焊接检验标准作业程序 (SOP)',
    categoryId: 'CAT-002-002',
    categoryName: 'SOP 程序文件',
    tags: ['焊接', '检验', 'SOP'],
    author: '工程技术部',
    publishDate: '2024-02-20',
    summary: '规范焊接过程中的外观及无损探伤检验流程。',
    content:
      '<h2>1. 目的</h2><p>确保焊接接头质量符合设计要求...</p><h2>2. 范围</h2><p>适用于所有压力容器焊接项目。</p>',
    status: 'published',
    version: 'V2.1',
    updatedAt: '2024-05-10 14:30:00',
    attachments: [],
  },
  {
    id: 'KB-1003',
    title: '液压泵密封失效案例分析',
    categoryId: 'CAT-003-001',
    categoryName: 'NCR 案例',
    tags: ['液压', '密封', '故障分析'],
    author: '售后服务部',
    publishDate: '2024-04-10',
    summary: '针对 Q1 季度出现的典型密封圈断裂问题进行的根本原因分析。',
    content:
      '<h3>问题描述</h3><p>在 WO-2024001 项目中发现...</p><h3>根本原因</h3><p>安装工具过紧导致应力集中。</p>',
    status: 'published',
    version: 'V1.0',
    updatedAt: '2024-04-12 09:00:00',
    attachments: [
      { name: '分析报告.docx', url: '#', size: 51_200, type: 'docx' },
    ],
  },
];

export const DETAILED_INSPECTIONS_LIST = [
  {
    id: 'REC-001',
    type: 'PROCESS',
    workOrderNumber: 'WO-2024001',
    projectName: '液压泵 X1',
    itpProjectId: 'ITP-PROJ-001',
    inspector: '张工',
    reportDate: '2024-05-15',
    status: 'COMPLETED',
    overallResult: 'PASS',
    results: [
      {
        itpItemId: 'ITP-ITEM-001',
        activity: '钢板材质检查',
        controlPoint: 'R',
        isQuantitative: true,
        standardValue: 20,
        upperTolerance: 0.5,
        lowerTolerance: 0.5,
        unit: 'mm',
        measuredValue: 20.1,
        result: 'PASS',
      },
      {
        itpItemId: 'ITP-ITEM-002',
        activity: '焊缝尺寸检查',
        controlPoint: 'W',
        isQuantitative: true,
        standardValue: 8,
        upperTolerance: 1,
        lowerTolerance: 1,
        unit: 'mm',
        measuredValue: 8.5,
        result: 'PASS',
      },
    ],
    createdAt: '2024-05-15 10:00:00',
    updatedAt: '2024-05-15 10:30:00',
  },
];

export const REPORTS_LIST = [
  {
    id: 'RPT-20240520',
    date: '2024-05-20',
    totalInspections: 45,
    passRate: 97.8,
    majorDefects: 1,
    minorDefects: 3,
    status: 'Published',
    author: 'Admin',
  },
  {
    id: 'RPT-20240521',
    date: '2024-05-21',
    totalInspections: 52,
    passRate: 96.1,
    majorDefects: 2,
    minorDefects: 5,
    status: 'Published',
    author: 'Admin',
  },
  {
    id: 'RPT-20240522',
    date: '2024-05-22',
    totalInspections: 48,
    passRate: 100,
    majorDefects: 0,
    minorDefects: 0,
    status: 'Draft',
    author: 'Admin',
  },
];
