export const SYSTEM_DEPT_LIST = [
  {
    id: '1',
    pid: '0',
    name: 'Headquarters',
    status: 1,
    createTime: '2023-01-01 12:00:00',
    remark: 'Global HQ',
    children: [
      {
        id: '2',
        pid: '1',
        name: 'R&D',
        status: 1,
        createTime: '2023-01-02 12:00:00',
        remark: 'Technical Center',
        children: [
          {
            id: '2-1',
            pid: '2',
            name: 'Software',
            status: 1,
            createTime: '2023-01-05',
            remark: 'App Dev',
          },
          {
            id: '2-2',
            pid: '2',
            name: 'Hardware',
            status: 1,
            createTime: '2023-01-05',
            remark: 'Device Dev',
          },
        ],
      },
      {
        id: '3',
        pid: '1',
        name: 'HR',
        status: 1,
        createTime: '2023-01-03 12:00:00',
        remark: 'Human Resources',
      },
      {
        id: '4',
        pid: '1',
        name: 'Sales',
        status: 1,
        createTime: '2023-01-04 12:00:00',
        remark: 'Global Sales',
      },
    ],
  },
];

export const SYSTEM_ROLE_LIST = [
  {
    id: '1',
    name: 'Super Admin',
    value: 'super',
    status: 1,
    createTime: '2023-01-01 10:00:00',
    remark: '超级管理员，拥有所有权限',
    permissions: [
      'System:Dept:List',
      'System:Dept:Create',
      'System:Dept:Edit',
      'System:Dept:Delete',
      'System:Role:List',
      'System:Role:Create',
      'System:Role:Edit',
      'System:Role:Delete',
      'System:Menu:List',
      'System:Menu:Create',
      'System:Menu:Edit',
      'System:Menu:Delete',
      'System:User:List',
      'System:User:Create',
      'System:User:Edit',
      'System:User:Delete',
      'QMS:WorkOrder:View',
      'QMS:WorkOrder:Create',
      'QMS:WorkOrder:Edit',
      'QMS:WorkOrder:Delete',
      'QMS:Inspection:View',
      'QMS:Inspection:Create',
      'QMS:Inspection:Edit',
      'QMS:Inspection:Delete',
      'QMS:AfterSales:View',
      'QMS:AfterSales:Create',
      'QMS:AfterSales:Edit',
      'QMS:AfterSales:Delete',
      'QMS:Supplier:View',
      'QMS:Supplier:Create',
      'QMS:Supplier:Edit',
      'QMS:Supplier:Delete',
      'QMS:Reports:View',
      'QMS:Reports:Export',
      'QMS:LossAnalysis:View',
      'QMS:Knowledge:View',
      'QMS:Knowledge:Create',
      'QMS:Knowledge:Edit',
      'QMS:Knowledge:Delete',
    ],
  },
  {
    id: '2',
    name: 'Admin',
    value: 'admin',
    status: 1,
    createTime: '2023-01-01 12:00:00',
    remark: '管理员，可管理大部分功能',
    permissions: [
      'System:Dept:List',
      'System:Dept:Create',
      'System:Dept:Edit',
      'System:Dept:Delete',
      'System:Role:List',
      'System:Role:Create',
      'System:Role:Edit',
      'System:Role:Delete',
      'System:Menu:List',
      'System:User:List',
      'System:User:Create',
      'System:User:Edit',
      'System:User:Delete',
      'QMS:WorkOrder:View',
      'QMS:WorkOrder:Create',
      'QMS:WorkOrder:Edit',
      'QMS:WorkOrder:Delete',
      'QMS:Inspection:View',
      'QMS:Inspection:Create',
      'QMS:Inspection:Edit',
      'QMS:Inspection:Delete',
      'QMS:AfterSales:View',
      'QMS:AfterSales:Create',
      'QMS:AfterSales:Edit',
      'QMS:AfterSales:Delete',
      'QMS:Supplier:View',
      'QMS:Supplier:Create',
      'QMS:Supplier:Edit',
      'QMS:Supplier:Delete',
      'QMS:Reports:View',
      'QMS:Reports:Export',
      'QMS:LossAnalysis:View',
      'QMS:Knowledge:View',
      'QMS:Knowledge:Create',
      'QMS:Knowledge:Edit',
    ],
  },
  {
    id: '3',
    name: 'User',
    value: 'user',
    status: 1,
    createTime: '2023-01-02 10:00:00',
    remark: '普通用户，可操作工单和质检',
    permissions: [
      'System:Dept:List',
      'System:Role:List',
      'QMS:WorkOrder:View',
      'QMS:WorkOrder:Create',
      'QMS:WorkOrder:Edit',
      'QMS:Inspection:View',
      'QMS:Inspection:Create',
      'QMS:Inspection:Edit',
      'QMS:AfterSales:View',
      'QMS:Supplier:View',
      'QMS:Reports:View',
      'QMS:Knowledge:View',
    ],
  },
  {
    id: '4',
    name: 'Guest',
    value: 'guest',
    status: 1,
    createTime: '2023-02-01 10:00:00',
    remark: '访客，仅可浏览',
    permissions: [
      'QMS:WorkOrder:View',
      'QMS:Inspection:View',
      'QMS:AfterSales:View',
      'QMS:Supplier:View',
    ],
  },
];

export const SYSTEM_MENU_LIST = [
  {
    id: 1,
    name: 'Workspace',
    status: 1,
    type: 'menu',
    icon: 'mdi:dashboard',
    path: '/workspace',
    component: '/dashboard/workspace/index',
    meta: {
      icon: 'carbon:workspace',
      title: '工作台',
      affixTab: true,
      order: 0,
    },
  },
  {
    id: 2,
    path: '/system',
    name: 'System',
    component: 'LAYOUT',
    meta: {
      title: '系统管理',
      icon: 'carbon:settings',
      order: 1000,
    },
    children: [
      {
        id: 201,
        path: '/system/menu',
        name: 'SystemMenu',
        component: '/system/menu/index',
        meta: {
          title: '菜单管理',
        },
      },
      {
        id: 202,
        path: '/system/dept',
        name: 'SystemDept',
        component: '/system/dept/index',
        meta: {
          title: '部门管理',
        },
      },
      {
        id: 203,
        path: '/system/role',
        name: 'SystemRole',
        component: '/system/role/index',
        meta: {
          title: '角色管理',
        },
      },
    ],
  },
];

export const SYSTEM_USER_LIST = [
  {
    id: '1',
    username: 'admin',
    realName: '管理员',
    email: 'admin@example.com',
    phone: '13800138000',
    deptId: '1',
    deptName: 'Headquarters',
    roleIds: ['1'],
    roles: ['super'],
    status: 1,
    createTime: '2023-01-01 10:00:00',
    remark: '超级管理员',
  },
  {
    id: '2',
    username: 'user',
    realName: '普通用户',
    email: 'user@example.com',
    phone: '13900139000',
    deptId: '2',
    deptName: 'R&D',
    roleIds: ['3'],
    roles: ['user'],
    status: 1,
    createTime: '2023-02-01 10:00:00',
    remark: '普通员工',
  },
  {
    id: '3',
    username: 'test',
    realName: '测试用户',
    email: 'test@example.com',
    phone: '13700137000',
    deptId: '3',
    deptName: 'HR',
    roleIds: ['3'],
    roles: ['user'],
    status: 0,
    createTime: '2023-03-01 10:00:00',
    remark: '已禁用账号',
  },
];

export const AI_SETTINGS = {
  provider: 'deepseek',
  apiKey: 'sk-xxxxxxxxxxxxxxxxxxxxxxxx',
  baseUrl: 'https://api.deepseek.com',
  model: 'deepseek-chat',
  availableModels: [
    'deepseek-chat',
    'deepseek-reasoner',
    'glm-4',
    'glm-4-flash',
    'gpt-3.5-turbo',
    'gpt-4o',
  ],
};
